//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.22 at 01:50:20 PM EDT 
//


package com.d6.schemas.work._2012_02.manhourmanagement;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 basic man hour info.
 *             
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="theMonthTmp" type="{http://d6.com/Schemas/Work/2012-02/ManHourManagement}ManHourMonthTmp" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="theProgramSet" type="{http://d6.com/Schemas/Work/2012-02/ManHourManagement}ManHourProgram" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="theBillTypeSet" type="{http://d6.com/Schemas/Work/2012-02/ManHourManagement}ManHourBillType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="myUserName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="myPosition" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="myYear" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="myMonth" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="totalDays" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="isHourlyBasedUser" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isManHourEditable" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "theMonthTmp",
    "theProgramSet",
    "theBillTypeSet"
})
@XmlRootElement(name = "ManHourInfo")
public class ManHourInfo
    implements Serializable
{

    protected List<ManHourMonthTmp> theMonthTmp;
    protected List<ManHourProgram> theProgramSet;
    protected List<ManHourBillType> theBillTypeSet;
    @XmlAttribute(required = true)
    protected String myUserName;
    @XmlAttribute(required = true)
    protected String myPosition;
    @XmlAttribute(required = true)
    protected String myYear;
    @XmlAttribute(required = true)
    protected String myMonth;
    @XmlAttribute(required = true)
    protected BigInteger totalDays;
    @XmlAttribute(required = true)
    protected boolean isHourlyBasedUser;
    @XmlAttribute(required = true)
    protected boolean isManHourEditable;

    /**
     * Gets the value of the theMonthTmp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the theMonthTmp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTheMonthTmp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ManHourMonthTmp }
     * 
     * 
     */
    public List<ManHourMonthTmp> getTheMonthTmp() {
        if (theMonthTmp == null) {
            theMonthTmp = new ArrayList<ManHourMonthTmp>();
        }
        return this.theMonthTmp;
    }

    public boolean isSetTheMonthTmp() {
        return ((this.theMonthTmp!= null)&&(!this.theMonthTmp.isEmpty()));
    }

    public void unsetTheMonthTmp() {
        this.theMonthTmp = null;
    }

    /**
     * Gets the value of the theProgramSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the theProgramSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTheProgramSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ManHourProgram }
     * 
     * 
     */
    public List<ManHourProgram> getTheProgramSet() {
        if (theProgramSet == null) {
            theProgramSet = new ArrayList<ManHourProgram>();
        }
        return this.theProgramSet;
    }

    public boolean isSetTheProgramSet() {
        return ((this.theProgramSet!= null)&&(!this.theProgramSet.isEmpty()));
    }

    public void unsetTheProgramSet() {
        this.theProgramSet = null;
    }

    /**
     * Gets the value of the theBillTypeSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the theBillTypeSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTheBillTypeSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ManHourBillType }
     * 
     * 
     */
    public List<ManHourBillType> getTheBillTypeSet() {
        if (theBillTypeSet == null) {
            theBillTypeSet = new ArrayList<ManHourBillType>();
        }
        return this.theBillTypeSet;
    }

    public boolean isSetTheBillTypeSet() {
        return ((this.theBillTypeSet!= null)&&(!this.theBillTypeSet.isEmpty()));
    }

    public void unsetTheBillTypeSet() {
        this.theBillTypeSet = null;
    }

    /**
     * Gets the value of the myUserName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMyUserName() {
        return myUserName;
    }

    /**
     * Sets the value of the myUserName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMyUserName(String value) {
        this.myUserName = value;
    }

    public boolean isSetMyUserName() {
        return (this.myUserName!= null);
    }

    /**
     * Gets the value of the myPosition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMyPosition() {
        return myPosition;
    }

    /**
     * Sets the value of the myPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMyPosition(String value) {
        this.myPosition = value;
    }

    public boolean isSetMyPosition() {
        return (this.myPosition!= null);
    }

    /**
     * Gets the value of the myYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMyYear() {
        return myYear;
    }

    /**
     * Sets the value of the myYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMyYear(String value) {
        this.myYear = value;
    }

    public boolean isSetMyYear() {
        return (this.myYear!= null);
    }

    /**
     * Gets the value of the myMonth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMyMonth() {
        return myMonth;
    }

    /**
     * Sets the value of the myMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMyMonth(String value) {
        this.myMonth = value;
    }

    public boolean isSetMyMonth() {
        return (this.myMonth!= null);
    }

    /**
     * Gets the value of the totalDays property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalDays() {
        return totalDays;
    }

    /**
     * Sets the value of the totalDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalDays(BigInteger value) {
        this.totalDays = value;
    }

    public boolean isSetTotalDays() {
        return (this.totalDays!= null);
    }

    /**
     * Gets the value of the isHourlyBasedUser property.
     * 
     */
    public boolean isIsHourlyBasedUser() {
        return isHourlyBasedUser;
    }

    /**
     * Sets the value of the isHourlyBasedUser property.
     * 
     */
    public void setIsHourlyBasedUser(boolean value) {
        this.isHourlyBasedUser = value;
    }

    public boolean isSetIsHourlyBasedUser() {
        return true;
    }

    /**
     * Gets the value of the isManHourEditable property.
     * 
     */
    public boolean isIsManHourEditable() {
        return isManHourEditable;
    }

    /**
     * Sets the value of the isManHourEditable property.
     * 
     */
    public void setIsManHourEditable(boolean value) {
        this.isManHourEditable = value;
    }

    public boolean isSetIsManHourEditable() {
        return true;
    }

}
