//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.22 at 01:50:20 PM EDT 
//


package com.d6.schemas.work._2012_02.manhourmanagement;

import java.io.Serializable;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 the month template for man hour.
 *             
 * 
 * <p>Java class for ManHourMonthTmp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ManHourMonthTmp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="dayOfMonth" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="dayOfWeek" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="isWeekend" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isHoliday" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="holidayName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="isWorkRequired" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ManHourMonthTmp")
public class ManHourMonthTmp
    implements Serializable
{

    @XmlAttribute(required = true)
    protected BigInteger dayOfMonth;
    @XmlAttribute(required = true)
    protected String dayOfWeek;
    @XmlAttribute(required = true)
    protected boolean isWeekend;
    @XmlAttribute(required = true)
    protected boolean isHoliday;
    @XmlAttribute(required = true)
    protected String holidayName;
    @XmlAttribute(required = true)
    protected boolean isWorkRequired;

    /**
     * Gets the value of the dayOfMonth property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDayOfMonth() {
        return dayOfMonth;
    }

    /**
     * Sets the value of the dayOfMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDayOfMonth(BigInteger value) {
        this.dayOfMonth = value;
    }

    public boolean isSetDayOfMonth() {
        return (this.dayOfMonth!= null);
    }

    /**
     * Gets the value of the dayOfWeek property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDayOfWeek() {
        return dayOfWeek;
    }

    /**
     * Sets the value of the dayOfWeek property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDayOfWeek(String value) {
        this.dayOfWeek = value;
    }

    public boolean isSetDayOfWeek() {
        return (this.dayOfWeek!= null);
    }

    /**
     * Gets the value of the isWeekend property.
     * 
     */
    public boolean isIsWeekend() {
        return isWeekend;
    }

    /**
     * Sets the value of the isWeekend property.
     * 
     */
    public void setIsWeekend(boolean value) {
        this.isWeekend = value;
    }

    public boolean isSetIsWeekend() {
        return true;
    }

    /**
     * Gets the value of the isHoliday property.
     * 
     */
    public boolean isIsHoliday() {
        return isHoliday;
    }

    /**
     * Sets the value of the isHoliday property.
     * 
     */
    public void setIsHoliday(boolean value) {
        this.isHoliday = value;
    }

    public boolean isSetIsHoliday() {
        return true;
    }

    /**
     * Gets the value of the holidayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHolidayName() {
        return holidayName;
    }

    /**
     * Sets the value of the holidayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHolidayName(String value) {
        this.holidayName = value;
    }

    public boolean isSetHolidayName() {
        return (this.holidayName!= null);
    }

    /**
     * Gets the value of the isWorkRequired property.
     * 
     */
    public boolean isIsWorkRequired() {
        return isWorkRequired;
    }

    /**
     * Sets the value of the isWorkRequired property.
     * 
     */
    public void setIsWorkRequired(boolean value) {
        this.isWorkRequired = value;
    }

    public boolean isSetIsWorkRequired() {
        return true;
    }

}
