//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.22 at 01:50:20 PM EDT 
//


package com.d6.schemas.work._2012_02.manhourmanagement;

import java.io.Serializable;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 the program info for the man hour.
 *             
 * 
 * <p>Java class for ManHourProgram complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ManHourProgram">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="prjId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="prjName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tskType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tskTypeDval" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="stkTag" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="startDay" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="endDay" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="prjStartYear" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="prjStartMonth" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="prjStartDay" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="prjEndYear" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="prjEndMonth" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="prjEndDay" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="schTag" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ManHourProgram")
public class ManHourProgram
    implements Serializable
{

    @XmlAttribute(required = true)
    protected String prjId;
    @XmlAttribute(required = true)
    protected String prjName;
    @XmlAttribute(required = true)
    protected String tskType;
    @XmlAttribute(required = true)
    protected String tskTypeDval;
    @XmlAttribute(required = true)
    protected String stkTag;
    @XmlAttribute(required = true)
    protected BigInteger startDay;
    @XmlAttribute(required = true)
    protected BigInteger endDay;
    @XmlAttribute(required = true)
    protected BigInteger prjStartYear;
    @XmlAttribute(required = true)
    protected BigInteger prjStartMonth;
    @XmlAttribute(required = true)
    protected BigInteger prjStartDay;
    @XmlAttribute(required = true)
    protected BigInteger prjEndYear;
    @XmlAttribute(required = true)
    protected BigInteger prjEndMonth;
    @XmlAttribute(required = true)
    protected BigInteger prjEndDay;
    @XmlAttribute(required = true)
    protected String schTag;

    /**
     * Gets the value of the prjId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrjId() {
        return prjId;
    }

    /**
     * Sets the value of the prjId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrjId(String value) {
        this.prjId = value;
    }

    public boolean isSetPrjId() {
        return (this.prjId!= null);
    }

    /**
     * Gets the value of the prjName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrjName() {
        return prjName;
    }

    /**
     * Sets the value of the prjName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrjName(String value) {
        this.prjName = value;
    }

    public boolean isSetPrjName() {
        return (this.prjName!= null);
    }

    /**
     * Gets the value of the tskType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTskType() {
        return tskType;
    }

    /**
     * Sets the value of the tskType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTskType(String value) {
        this.tskType = value;
    }

    public boolean isSetTskType() {
        return (this.tskType!= null);
    }

    /**
     * Gets the value of the tskTypeDval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTskTypeDval() {
        return tskTypeDval;
    }

    /**
     * Sets the value of the tskTypeDval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTskTypeDval(String value) {
        this.tskTypeDval = value;
    }

    public boolean isSetTskTypeDval() {
        return (this.tskTypeDval!= null);
    }

    /**
     * Gets the value of the stkTag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStkTag() {
        return stkTag;
    }

    /**
     * Sets the value of the stkTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStkTag(String value) {
        this.stkTag = value;
    }

    public boolean isSetStkTag() {
        return (this.stkTag!= null);
    }

    /**
     * Gets the value of the startDay property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStartDay() {
        return startDay;
    }

    /**
     * Sets the value of the startDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStartDay(BigInteger value) {
        this.startDay = value;
    }

    public boolean isSetStartDay() {
        return (this.startDay!= null);
    }

    /**
     * Gets the value of the endDay property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEndDay() {
        return endDay;
    }

    /**
     * Sets the value of the endDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEndDay(BigInteger value) {
        this.endDay = value;
    }

    public boolean isSetEndDay() {
        return (this.endDay!= null);
    }

    /**
     * Gets the value of the prjStartYear property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPrjStartYear() {
        return prjStartYear;
    }

    /**
     * Sets the value of the prjStartYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPrjStartYear(BigInteger value) {
        this.prjStartYear = value;
    }

    public boolean isSetPrjStartYear() {
        return (this.prjStartYear!= null);
    }

    /**
     * Gets the value of the prjStartMonth property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPrjStartMonth() {
        return prjStartMonth;
    }

    /**
     * Sets the value of the prjStartMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPrjStartMonth(BigInteger value) {
        this.prjStartMonth = value;
    }

    public boolean isSetPrjStartMonth() {
        return (this.prjStartMonth!= null);
    }

    /**
     * Gets the value of the prjStartDay property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPrjStartDay() {
        return prjStartDay;
    }

    /**
     * Sets the value of the prjStartDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPrjStartDay(BigInteger value) {
        this.prjStartDay = value;
    }

    public boolean isSetPrjStartDay() {
        return (this.prjStartDay!= null);
    }

    /**
     * Gets the value of the prjEndYear property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPrjEndYear() {
        return prjEndYear;
    }

    /**
     * Sets the value of the prjEndYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPrjEndYear(BigInteger value) {
        this.prjEndYear = value;
    }

    public boolean isSetPrjEndYear() {
        return (this.prjEndYear!= null);
    }

    /**
     * Gets the value of the prjEndMonth property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPrjEndMonth() {
        return prjEndMonth;
    }

    /**
     * Sets the value of the prjEndMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPrjEndMonth(BigInteger value) {
        this.prjEndMonth = value;
    }

    public boolean isSetPrjEndMonth() {
        return (this.prjEndMonth!= null);
    }

    /**
     * Gets the value of the prjEndDay property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPrjEndDay() {
        return prjEndDay;
    }

    /**
     * Sets the value of the prjEndDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPrjEndDay(BigInteger value) {
        this.prjEndDay = value;
    }

    public boolean isSetPrjEndDay() {
        return (this.prjEndDay!= null);
    }

    /**
     * Gets the value of the schTag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchTag() {
        return schTag;
    }

    /**
     * Sets the value of the schTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchTag(String value) {
        this.schTag = value;
    }

    public boolean isSetSchTag() {
        return (this.schTag!= null);
    }

}
