//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.22 at 01:50:20 PM EDT 
//


package com.d6.schemas.work._2012_02.manhourmanagement;

import java.io.Serializable;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 man hour enty
 *             
 * 
 * <p>Java class for ManHourEntry complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ManHourEntry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="myUserName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="myYear" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="myMonth" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="myDay" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="myDayOfWeek" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="myHoliday" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="workRequired" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="myPrjName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="myPrjId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="myTaskType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="myTaskTypeDval" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="billType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="myRefBR" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="workingHours" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="myRefTE" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tseStatus" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="myRefMHE" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="row" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="col" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="billTypeInternal" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ManHourEntry")
public class ManHourEntry
    implements Serializable
{

    @XmlAttribute(required = true)
    protected String myUserName;
    @XmlAttribute(required = true)
    protected String myYear;
    @XmlAttribute(required = true)
    protected String myMonth;
    @XmlAttribute(required = true)
    protected String myDay;
    @XmlAttribute(required = true)
    protected String myDayOfWeek;
    @XmlAttribute(required = true)
    protected String myHoliday;
    @XmlAttribute(required = true)
    protected String workRequired;
    @XmlAttribute(required = true)
    protected String myPrjName;
    @XmlAttribute(required = true)
    protected String myPrjId;
    @XmlAttribute(required = true)
    protected String myTaskType;
    @XmlAttribute(required = true)
    protected String myTaskTypeDval;
    @XmlAttribute(required = true)
    protected String billType;
    @XmlAttribute(required = true)
    protected String myRefBR;
    @XmlAttribute(required = true)
    protected String workingHours;
    @XmlAttribute(required = true)
    protected String myRefTE;
    @XmlAttribute(required = true)
    protected String tseStatus;
    @XmlAttribute(required = true)
    protected String myRefMHE;
    @XmlAttribute(required = true)
    protected BigInteger row;
    @XmlAttribute(required = true)
    protected BigInteger col;
    @XmlAttribute(required = true)
    protected String billTypeInternal;

    /**
     * Gets the value of the myUserName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMyUserName() {
        return myUserName;
    }

    /**
     * Sets the value of the myUserName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMyUserName(String value) {
        this.myUserName = value;
    }

    public boolean isSetMyUserName() {
        return (this.myUserName!= null);
    }

    /**
     * Gets the value of the myYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMyYear() {
        return myYear;
    }

    /**
     * Sets the value of the myYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMyYear(String value) {
        this.myYear = value;
    }

    public boolean isSetMyYear() {
        return (this.myYear!= null);
    }

    /**
     * Gets the value of the myMonth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMyMonth() {
        return myMonth;
    }

    /**
     * Sets the value of the myMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMyMonth(String value) {
        this.myMonth = value;
    }

    public boolean isSetMyMonth() {
        return (this.myMonth!= null);
    }

    /**
     * Gets the value of the myDay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMyDay() {
        return myDay;
    }

    /**
     * Sets the value of the myDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMyDay(String value) {
        this.myDay = value;
    }

    public boolean isSetMyDay() {
        return (this.myDay!= null);
    }

    /**
     * Gets the value of the myDayOfWeek property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMyDayOfWeek() {
        return myDayOfWeek;
    }

    /**
     * Sets the value of the myDayOfWeek property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMyDayOfWeek(String value) {
        this.myDayOfWeek = value;
    }

    public boolean isSetMyDayOfWeek() {
        return (this.myDayOfWeek!= null);
    }

    /**
     * Gets the value of the myHoliday property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMyHoliday() {
        return myHoliday;
    }

    /**
     * Sets the value of the myHoliday property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMyHoliday(String value) {
        this.myHoliday = value;
    }

    public boolean isSetMyHoliday() {
        return (this.myHoliday!= null);
    }

    /**
     * Gets the value of the workRequired property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkRequired() {
        return workRequired;
    }

    /**
     * Sets the value of the workRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkRequired(String value) {
        this.workRequired = value;
    }

    public boolean isSetWorkRequired() {
        return (this.workRequired!= null);
    }

    /**
     * Gets the value of the myPrjName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMyPrjName() {
        return myPrjName;
    }

    /**
     * Sets the value of the myPrjName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMyPrjName(String value) {
        this.myPrjName = value;
    }

    public boolean isSetMyPrjName() {
        return (this.myPrjName!= null);
    }

    /**
     * Gets the value of the myPrjId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMyPrjId() {
        return myPrjId;
    }

    /**
     * Sets the value of the myPrjId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMyPrjId(String value) {
        this.myPrjId = value;
    }

    public boolean isSetMyPrjId() {
        return (this.myPrjId!= null);
    }

    /**
     * Gets the value of the myTaskType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMyTaskType() {
        return myTaskType;
    }

    /**
     * Sets the value of the myTaskType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMyTaskType(String value) {
        this.myTaskType = value;
    }

    public boolean isSetMyTaskType() {
        return (this.myTaskType!= null);
    }

    /**
     * Gets the value of the myTaskTypeDval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMyTaskTypeDval() {
        return myTaskTypeDval;
    }

    /**
     * Sets the value of the myTaskTypeDval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMyTaskTypeDval(String value) {
        this.myTaskTypeDval = value;
    }

    public boolean isSetMyTaskTypeDval() {
        return (this.myTaskTypeDval!= null);
    }

    /**
     * Gets the value of the billType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillType() {
        return billType;
    }

    /**
     * Sets the value of the billType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillType(String value) {
        this.billType = value;
    }

    public boolean isSetBillType() {
        return (this.billType!= null);
    }

    /**
     * Gets the value of the myRefBR property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMyRefBR() {
        return myRefBR;
    }

    /**
     * Sets the value of the myRefBR property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMyRefBR(String value) {
        this.myRefBR = value;
    }

    public boolean isSetMyRefBR() {
        return (this.myRefBR!= null);
    }

    /**
     * Gets the value of the workingHours property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkingHours() {
        return workingHours;
    }

    /**
     * Sets the value of the workingHours property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkingHours(String value) {
        this.workingHours = value;
    }

    public boolean isSetWorkingHours() {
        return (this.workingHours!= null);
    }

    /**
     * Gets the value of the myRefTE property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMyRefTE() {
        return myRefTE;
    }

    /**
     * Sets the value of the myRefTE property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMyRefTE(String value) {
        this.myRefTE = value;
    }

    public boolean isSetMyRefTE() {
        return (this.myRefTE!= null);
    }

    /**
     * Gets the value of the tseStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTseStatus() {
        return tseStatus;
    }

    /**
     * Sets the value of the tseStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTseStatus(String value) {
        this.tseStatus = value;
    }

    public boolean isSetTseStatus() {
        return (this.tseStatus!= null);
    }

    /**
     * Gets the value of the myRefMHE property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMyRefMHE() {
        return myRefMHE;
    }

    /**
     * Sets the value of the myRefMHE property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMyRefMHE(String value) {
        this.myRefMHE = value;
    }

    public boolean isSetMyRefMHE() {
        return (this.myRefMHE!= null);
    }

    /**
     * Gets the value of the row property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRow() {
        return row;
    }

    /**
     * Sets the value of the row property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRow(BigInteger value) {
        this.row = value;
    }

    public boolean isSetRow() {
        return (this.row!= null);
    }

    /**
     * Gets the value of the col property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCol() {
        return col;
    }

    /**
     * Sets the value of the col property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCol(BigInteger value) {
        this.col = value;
    }

    public boolean isSetCol() {
        return (this.col!= null);
    }

    /**
     * Gets the value of the billTypeInternal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillTypeInternal() {
        return billTypeInternal;
    }

    /**
     * Sets the value of the billTypeInternal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillTypeInternal(String value) {
        this.billTypeInternal = value;
    }

    public boolean isSetBillTypeInternal() {
        return (this.billTypeInternal!= null);
    }

}
