//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.22 at 01:50:20 PM EDT 
//


package com.d6.schemas.work._2012_02.manhourmanagement;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 a set of man hour entries
 *             
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mheSet" type="{http://d6.com/Schemas/Work/2012-02/ManHourManagement}ManHourEntry" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mheSet"
})
@XmlRootElement(name = "ManHourEntrySet")
public class ManHourEntrySet
    implements Serializable
{

    protected List<ManHourEntry> mheSet;

    /**
     * Gets the value of the mheSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mheSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMheSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ManHourEntry }
     * 
     * 
     */
    public List<ManHourEntry> getMheSet() {
        if (mheSet == null) {
            mheSet = new ArrayList<ManHourEntry>();
        }
        return this.mheSet;
    }

    public boolean isSetMheSet() {
        return ((this.mheSet!= null)&&(!this.mheSet.isEmpty()));
    }

    public void unsetMheSet() {
        this.mheSet = null;
    }

}
