//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.22 at 01:50:20 PM EDT 
//


package com.d6.schemas.work._2012_02.manhourmanagement;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 BillType
 *             
 * 
 * <p>Java class for ManHourBillType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ManHourBillType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="myRefBR" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="billTypeInternal" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="billRateName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ManHourBillType")
public class ManHourBillType
    implements Serializable
{

    @XmlAttribute(required = true)
    protected String myRefBR;
    @XmlAttribute(required = true)
    protected String billTypeInternal;
    @XmlAttribute(required = true)
    protected String billRateName;

    /**
     * Gets the value of the myRefBR property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMyRefBR() {
        return myRefBR;
    }

    /**
     * Sets the value of the myRefBR property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMyRefBR(String value) {
        this.myRefBR = value;
    }

    public boolean isSetMyRefBR() {
        return (this.myRefBR!= null);
    }

    /**
     * Gets the value of the billTypeInternal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillTypeInternal() {
        return billTypeInternal;
    }

    /**
     * Sets the value of the billTypeInternal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillTypeInternal(String value) {
        this.billTypeInternal = value;
    }

    public boolean isSetBillTypeInternal() {
        return (this.billTypeInternal!= null);
    }

    /**
     * Gets the value of the billRateName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillRateName() {
        return billRateName;
    }

    /**
     * Sets the value of the billRateName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillRateName(String value) {
        this.billRateName = value;
    }

    public boolean isSetBillRateName() {
        return (this.billRateName!= null);
    }

}
