//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.22 at 01:50:20 PM EDT 
//


package com.d6.schemas.work._2012_02.manhourmanagement;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.d6.schemas.work._2012_02.manhourmanagement package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.d6.schemas.work._2012_02.manhourmanagement
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ManHourInfo }
     * 
     */
    public ManHourInfo createManHourInfo() {
        return new ManHourInfo();
    }

    /**
     * Create an instance of {@link ClearManHoursOutput }
     * 
     */
    public ClearManHoursOutput createClearManHoursOutput() {
        return new ClearManHoursOutput();
    }

    /**
     * Create an instance of {@link LoadInput }
     * 
     */
    public LoadInput createLoadInput() {
        return new LoadInput();
    }

    /**
     * Create an instance of {@link MheTestOutput }
     * 
     */
    public MheTestOutput createMheTestOutput() {
        return new MheTestOutput();
    }

    /**
     * Create an instance of {@link ClearManHoursInput }
     * 
     */
    public ClearManHoursInput createClearManHoursInput() {
        return new ClearManHoursInput();
    }

    /**
     * Create an instance of {@link MheTestInput }
     * 
     */
    public MheTestInput createMheTestInput() {
        return new MheTestInput();
    }

    /**
     * Create an instance of {@link SaveInput }
     * 
     */
    public SaveInput createSaveInput() {
        return new SaveInput();
    }

    /**
     * Create an instance of {@link ManHourProgram }
     * 
     */
    public ManHourProgram createManHourProgram() {
        return new ManHourProgram();
    }

    /**
     * Create an instance of {@link ManHourEntrySet }
     * 
     */
    public ManHourEntrySet createManHourEntrySet() {
        return new ManHourEntrySet();
    }

    /**
     * Create an instance of {@link ManHourMonthTmp }
     * 
     */
    public ManHourMonthTmp createManHourMonthTmp() {
        return new ManHourMonthTmp();
    }

    /**
     * Create an instance of {@link GetManHourInfoInput }
     * 
     */
    public GetManHourInfoInput createGetManHourInfoInput() {
        return new GetManHourInfoInput();
    }

    /**
     * Create an instance of {@link ManHourEntry }
     * 
     */
    public ManHourEntry createManHourEntry() {
        return new ManHourEntry();
    }

    /**
     * Create an instance of {@link ReviseInput }
     * 
     */
    public ReviseInput createReviseInput() {
        return new ReviseInput();
    }

    /**
     * Create an instance of {@link ManHourBillType }
     * 
     */
    public ManHourBillType createManHourBillType() {
        return new ManHourBillType();
    }

}
