//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.22 at 01:50:20 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://d6.com/Schemas/Work/2012-02/ManHourManagement", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.d6.schemas.work._2012_02.manhourmanagement;
