//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.22 at 01:50:20 PM EDT 
//


package com.d6.schemas.work._2012_02.manhourmanagement;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="manHours" type="{http://d6.com/Schemas/Work/2012-02/ManHourManagement}ManHourEntry" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="thePrograms" type="{http://d6.com/Schemas/Work/2012-02/ManHourManagement}ManHourProgram" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="theUserName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="theYear" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="theMonth" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "manHours",
    "thePrograms"
})
@XmlRootElement(name = "SaveInput")
public class SaveInput
    implements Serializable
{

    protected List<ManHourEntry> manHours;
    protected List<ManHourProgram> thePrograms;
    @XmlAttribute(required = true)
    protected String theUserName;
    @XmlAttribute(required = true)
    protected String theYear;
    @XmlAttribute(required = true)
    protected String theMonth;

    /**
     * Gets the value of the manHours property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the manHours property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getManHours().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ManHourEntry }
     * 
     * 
     */
    public List<ManHourEntry> getManHours() {
        if (manHours == null) {
            manHours = new ArrayList<ManHourEntry>();
        }
        return this.manHours;
    }

    public boolean isSetManHours() {
        return ((this.manHours!= null)&&(!this.manHours.isEmpty()));
    }

    public void unsetManHours() {
        this.manHours = null;
    }

    /**
     * Gets the value of the thePrograms property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the thePrograms property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getThePrograms().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ManHourProgram }
     * 
     * 
     */
    public List<ManHourProgram> getThePrograms() {
        if (thePrograms == null) {
            thePrograms = new ArrayList<ManHourProgram>();
        }
        return this.thePrograms;
    }

    public boolean isSetThePrograms() {
        return ((this.thePrograms!= null)&&(!this.thePrograms.isEmpty()));
    }

    public void unsetThePrograms() {
        this.thePrograms = null;
    }

    /**
     * Gets the value of the theUserName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTheUserName() {
        return theUserName;
    }

    /**
     * Sets the value of the theUserName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTheUserName(String value) {
        this.theUserName = value;
    }

    public boolean isSetTheUserName() {
        return (this.theUserName!= null);
    }

    /**
     * Gets the value of the theYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTheYear() {
        return theYear;
    }

    /**
     * Sets the value of the theYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTheYear(String value) {
        this.theYear = value;
    }

    public boolean isSetTheYear() {
        return (this.theYear!= null);
    }

    /**
     * Gets the value of the theMonth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTheMonth() {
        return theMonth;
    }

    /**
     * Sets the value of the theMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTheMonth(String value) {
        this.theMonth = value;
    }

    public boolean isSetTheMonth() {
        return (this.theMonth!= null);
    }

}
