/* 
 @<COPYRIGHT>@
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 @<COPYRIGHT>@

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libd6soawork

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use SOAWORK_API, not SOAWORKEXPORT */

#define SOAWORK_API SOAWORKEXPORT

/* Support SOAWORKEXPORT for autogenerated schema/pif code only */

#if IPLIB==libd6soawork
#   if defined(__lint)
#       define SOAWORKEXPORT       __export(d6soawork)
#       define SOAWORKGLOBAL       extern __global(d6soawork)
#       define SOAWORKPRIVATE      extern __private(d6soawork)
#   elif defined(_WIN32)
#       define SOAWORKEXPORT       __declspec(dllexport)
#       define SOAWORKGLOBAL       extern __declspec(dllexport)
#       define SOAWORKPRIVATE      extern
#   else
#       define SOAWORKEXPORT
#       define SOAWORKGLOBAL       extern
#       define SOAWORKPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define SOAWORKEXPORT       __export(d6soawork)
#       define SOAWORKGLOBAL       extern __global(d6soawork)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define SOAWORKEXPORT      __declspec(dllimport)
#       define SOAWORKGLOBAL       extern __declspec(dllimport)
#   else
#       define SOAWORKEXPORT
#       define SOAWORKGLOBAL       extern
#   endif
#endif

