/* 
 @<COPYRIGHT>@
 ==================================================
 Copyright 2012
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 @<COPYRIGHT>@

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libtcsoamodeld6st

#if !defined(IPLIB)
#   error IPLIB is not defined
#endif

/* Handwritten code should use TCSOAD6STMODEL_API, not TCSOAD6STMODELEXPORT */

#define TCSOAD6STMODEL_API TCSOAD6STMODELEXPORT

/* Support TCSOAD6STMODELEXPORT for autogenerated schema/pif code only */

#if IPLIB==libtcsoamodeld6st
#   if defined(__lint)
#       define TCSOAD6STMODELEXPORT       __export(tcsoamodeld6st)
#       define TCSOAD6STMODELGLOBAL       extern __global(tcsoamodeld6st)
#       define TCSOAD6STMODELPRIVATE      extern __private(tcsoamodeld6st)
#   elif defined(_WIN32)
#       define TCSOAD6STMODELEXPORT       __declspec(dllexport)
#       define TCSOAD6STMODELGLOBAL       extern __declspec(dllexport)
#       define TCSOAD6STMODELPRIVATE      extern
#   else
#       define TCSOAD6STMODELEXPORT
#       define TCSOAD6STMODELGLOBAL       extern
#       define TCSOAD6STMODELPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define TCSOAD6STMODELEXPORT       __export(tcsoamodeld6st)
#       define TCSOAD6STMODELGLOBAL       extern __global(tcsoamodeld6st)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define TCSOAD6STMODELEXPORT      __declspec(dllimport)
#       define TCSOAD6STMODELGLOBAL       extern __declspec(dllimport)
#   else
#       define TCSOAD6STMODELEXPORT
#       define TCSOAD6STMODELGLOBAL       extern
#   endif
#endif

