/* 
 @<COPYRIGHT>@
 ==================================================
 Copyright 2015
 Siemens Product Lifecycle Management Software Inc.
 All Rights Reserved.
 ==================================================
 @<COPYRIGHT>@

 ==================================================

   Auto-generated source from service interface.
                 DO NOT EDIT

 ==================================================
*/

#include <common/library_indicators.h>

#ifdef EXPORTLIBRARY
#define EXPORTLIBRARY something else
#error ExportLibrary was already defined
#endif

#define EXPORTLIBRARY            libd9soaworkstrongmngd

#if !defined(IPLIB)
#define IPLIB 0
#endif

/* Handwritten code should use D9SOAWORKSTRONGMNGD_API, not D9SOAWORKSTRONGMNGDEXPORT */

#define D9SOAWORKSTRONGMNGD_API D9SOAWORKSTRONGMNGDEXPORT

/* Support D9SOAWORKSTRONGMNGDEXPORT for autogenerated schema/pif code only */

#if IPLIB==libd9soaworkstrongmngd
#   if defined(__lint)
#       define D9SOAWORKSTRONGMNGDEXPORT       __export(d9soaworkstrongmngd)
#       define D9SOAWORKSTRONGMNGDGLOBAL       extern __global(d9soaworkstrongmngd)
#       define D9SOAWORKSTRONGMNGDPRIVATE      extern __private(d9soaworkstrongmngd)
#   elif defined(_WIN32)
#       define D9SOAWORKSTRONGMNGDEXPORT       __declspec(dllexport)
#       define D9SOAWORKSTRONGMNGDGLOBAL       extern __declspec(dllexport)
#       define D9SOAWORKSTRONGMNGDPRIVATE      extern
#   else
#       define D9SOAWORKSTRONGMNGDEXPORT
#       define D9SOAWORKSTRONGMNGDGLOBAL       extern
#       define D9SOAWORKSTRONGMNGDPRIVATE      extern
#   endif
#else
#   if defined(__lint)
#       define D9SOAWORKSTRONGMNGDEXPORT       __export(d9soaworkstrongmngd)
#       define D9SOAWORKSTRONGMNGDGLOBAL       extern __global(d9soaworkstrongmngd)
#   elif defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define D9SOAWORKSTRONGMNGDEXPORT      __declspec(dllimport)
#       define D9SOAWORKSTRONGMNGDGLOBAL       extern __declspec(dllimport)
#   else
#       define D9SOAWORKSTRONGMNGDEXPORT
#       define D9SOAWORKSTRONGMNGDGLOBAL       extern
#   endif
#endif

