#
# makefile for d6st Project
#


include output/soamakefile
all : d6st_prj

d6st_prj : bldmsg 
	@echo -----------------------------------
	@echo Successful build of all Libraries for d6st
	@echo -----------------------------------

bldmsg :
	@echo -----------------------------------
	@echo Building ALL libraries for d6st
	@echo -----------------------------------

CLEAN : Clean_message

Clean_message :
	@echo -----------------------------------
	@echo CLEANING Build Project directorys for d6st
	@echo -----------------------------------

